application: habitalt
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(reflecting|welcome|u)?
  static_files: public/index.html
  upload: public/index.html
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
- url: /stylesheets
  static_dir: public/stylesheets
- url: /js
  static_dir: public/js

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
